name: Upgrade
on:
    workflow_dispatch:
    schedule:
        - cron: '20 4 * * *'
jobs:
    npm-check-updates:
        if: (github.event_name == 'schedule' && github.repository == 'stolostron/react-data-view') || (github.event_name != 'schedule')
        runs-on: ubuntu-latest
        concurrency: react-data-view
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GH_TOKEN }}
            - uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  registry-url: https://registry.npmjs.org/
                  cache: npm
            - run: npm run upgrade
            - uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  message: Upgraded package dependencies
